name: Setup Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  setup-gradle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Generate Gradle Wrapper
      run: |
        gradle wrapper
        chmod +x gradlew
        git add gradlew gradlew.bat gradle/
        git commit -m "Add Gradle wrapper files"
        git push origin HEAD
